### ISSUE TITLE
Check / better specification of street directions 

### ISSUE THREAD

**Issue by rotger711** [openbikesensor/portal#208] opened 2022-02-27 15:07 UTC
On the beta Portal (portal.openbiksensor.org) I have the impression that some of the street segments (not all) mix up the direction (e.g here when you look at the [two red segments on Neue Weinsteige](https://portal.openbikesensor.org/map#16.11/48.76493277937638/9.17881441915424), left one (south bound) is uphill with lots of passings, right one (north bound) is downhill with very little overtakings. The vizualisation suggests the opposite. On some other segments this seems not too clear, see e.g. the [one-way-segment in Kaltental with its now 332 events](https://portal.openbikesensor.org/map#17.11/48.74290441432527/9.133668985130292) (wow!). 
Maybe its be better to make a choice between separate statistics for each direction in any street segment (klick on one of the two lines) plus the option to make a second evaluation for both directions together?

**Comment by opatut** [comment] 2022-03-03 13:33
Duplicate of #142 , fixed in 0.4.0.

**Closed by opatut** 2022-03-03 13:33 UTC
Labels: bug
