### ISSUE TITLE
Mobile page hard to use

### ISSUE THREAD

**Issue by gluap** [openbikesensor/portal#213] opened 2022-03-04 19:38 UTC
@boldt noticed that the map page is hard to use on mobile screens.

Namely:
- the statistics display covers the burger menu and almost the whole map on vertical screen
- roads are almost impossible to click and if clicked the statistics cover the map almost entirely 

Marking this as enhancement as i assume most people will have a desktop or tablet for proper viewing and mobile is "second". Also marking as Javascript as it is a pure frontend thing. 

![Screenshot_20220304-201050.png](https://user-images.githubusercontent.com/44007906/156830131-55afd51e-f912-4198-9d41-868f920aa7ab.png)![Screenshot_20220304-200801.png](https://user-images.githubusercontent.com/44007906/156830140-3024d892-51e2-43a4-b181-d6a74e1d23b2.png)

**Comment by opatut** [comment] 2022-04-02 19:26
Duplicate of #129

**Closed** 2022-04-02 19:27 UTC
Labels: enhancement, javascript
